### ISSUE TITLE
Keyboard shortcuts enhancements

### ISSUE THREAD

**Issue by pravdomil** [alfredapp/openai-workflow#26]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Feature details

```
↩ Ask question  OK
⌘↩ New Chat     OK - but do not auto send the prompt in the new chat, just populate the input field
⌥↩ Copy Last    ⌘C (if there is no text selection)
⌃↩ Copy All     ⌥⌘C (if there is no text selection)
⇧↩ Stop         Esc
New Line        ⌥↩
Next Chat       ??
Previous Chat   ??
```

**Comment by vitorgalvao** [comment]
Most of those won’t work. You can’t just override <kbd>⌘</kbd><kbd>C</kbd> in that manner and <kbd>esc</kbd> closes the window so it can’t be used to interrupt because it’s a feature that it can continue writing the answer when the window is closed.

There are no plans to change the available shortcuts at this time.
