### ISSUE TITLE
Do not use headers for user prompts

### ISSUE THREAD

**Issue by pravdomil** [alfredapp/openai-workflow#28]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Feature details

if you enter code
it gets messy
I can design something for you

<img width="764" alt="image" src="https://github.com/alfredapp/openai-workflow/assets/2387356/20d6300f-6eff-4c70-a14d-1bf9e04b3696">

**Comment by vitorgalvao** [comment]
There’s nothing to design, the text is parsed markdown. User input is shown as a header, which makes sense for the overwhelming majority of cases.

**Comment by pravdomil** [comment]
you are not even open to have discussion, you straight go for there is nothing to design, wow

**Comment by vitorgalvao** [comment]
That is because the window is not freeform, it is parsing markdown input. There is nothing you *can* design. As stated in another issue, this workflow has a lot of users—many of whom are non-technical—and their needs have to be met as well. A clear separation of user input and response is crucial.

Note the full code is available in the workflow and you can change it at will for your local setup.
