### ISSUE TITLE
Can't get it to work ... no resutls are being returned ... command enter does nothing .. 

### ISSUE THREAD

**Issue by momomo** [alfredapp/openai-workflow#51]
### Frequently Asked Questions

- [X] I have [read the FAQ](../blob/main/FAQ.md) before opening the issue.

### Feature details

See  title ...

Gets stuck on this: 
![image](https://github.com/user-attachments/assets/d81d125b-a974-485f-92d4-6ef9366447b9)

Nothing really loads. I can get to empty chat history but nothing is there obviously ... nothing is being sent ... just installed in on latest alfred. 

Nothing happens on Enter or option Enter ... 

![image](https://github.com/user-attachments/assets/b33706c1-e7f0-418f-be7d-515c4e7e049e)
Here i changed the key from chat to ]

**Comment by vitorgalvao** [comment]
This is not a feature request. Please open the correct template, for bug reports, and carefully fill *all* the requested information, including exact versions and debugger output. And please do be sure to really read the FAQ and not just tick the box, as it also explains in detail what’s necessary for a bug report and what to do when you think nothing is happening.

It only takes a minute to follow the instructions and it saves us hours of back and forth. Help me help you.

Finally, if you’re requesting assistance don’t modify the workflow, that hinders my ability to know what could be going wrong.

**Comment by momomo** [comment]
Sorry but I don't work for you. You've complicated the bug reporting too much. I will leave it here, you investigate it or not, but it does not work. I've tried plenty and given up.

**Comment by vitorgalvao** [comment]
It does work. Thousands of people use the workflow. Whatever you are experiencing is undoubtedly on your side.

You are probably [missing the Automation Tasks](https://www.alfredapp.com/help/kb/automation-task-not-found/), which is [explained in the FAQ](https://github.com/alfredapp/openai-workflow/blob/main/FAQ.md#why-does-nothing-happen-when-i-run-the-workflow) and pointed out when running the [debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/), which you _always_ have to do to report any issue with any workflow because otherwise it’s impossible for a developer to know what is happening on your side.

**Comment by vitorgalvao** [comment]
I edited your post to remove the screenshot with the API key, you don’t want to be public.

That response comes directly from the API, so OpenAI are the ones who’ll be able to say specifically. But yes, you do need to buy credits to use the API, [a ChatGPT Plus subscription is a different thing](https://github.com/alfredapp/openai-workflow/blob/main/FAQ.md#why-cant-i-use-the-workflow-with-a-chatgpt-plus-subscription).
